modelagem exportada

-- MySQL Script generated by MySQL Workbench
-- 05/13/26 12:13:00
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`armario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`armario` (
  `cdArmario` INT NOT NULL,
  `nmArmario` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`cdArmario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Aluno`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Aluno` (
  `cdAluno` INT NOT NULL,
  `nmAluno` VARCHAR(45) NOT NULL,
  `cdArmario` INT NOT NULL,
  PRIMARY KEY (`cdAluno`),
  INDEX `AlunoArmario_idx` (`cdArmario` ASC),
  CONSTRAINT `AlunoArmario`
    FOREIGN KEY (`cdArmario`)
    REFERENCES `mydb`.`armario` (`cdArmario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
